### ISSUE TITLE
milestone is not working

### ISSUE THREAD

**Issue by megos** [ksoichiro/gitlab-i18n-patch#5]
#### 概要
- v8.13.3
マイルストーンが1つ以上ある状態でマイルストーンを開くと500エラーが発生します。
下記2つのファイルで```milestone: milestone```となっているところを```milestone: マイルストーン```と置換しているためだと思います。

- ```app/views/groups/milestones/_milestone.html.haml```
- ```app/views/projects/milestones/_milestone.html.haml```

#### ログ
```
ActionView::Template::Error (undefined local variable or method `マイルストーン' for #<#<Class:0x007fdc0c11db00>:0x007fdc0c0dc010>):
    1: = render 'shared/milestones/milestone',
    2:           milestone_path: namespace_project_milestone_path(milestone.project.namespace, milestone.project, milestone),
    3:           issues_path: namespace_project_issues_path(milestone.project.namespace, milestone.project, milestone_title: milestone.title),
    4:           merge_requests_path: namespace_project_merge_requests_path(milestone.project.namespace, milestone.project, milestone_title: milestone.title),
  app/views/projects/milestones/_milestone.html.haml:1:in `_app_views_projects_milestones__milestone_html_haml___776277496364141360_70291543729040'
  app/views/projects/milestones/index.html.haml:16:in `_app_views_projects_milestones_index_html_haml___3288182732046808079_70291535867760'
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
```

**Comment by ksoichiro** [comment]
ご指摘ありがとうございました！PRをマージしました。

**Comment by megos** [comment]
ありがとうございました。   
今後ともよろしくお願いします。
