### ISSUE TITLE
System OAuth applications is not working (500 Error)

### ISSUE THREAD

**Issue by hir-of** [ksoichiro/gitlab-i18n-patch#8]
## 概要

* 8.15.4で確認(恐らく以前のバージョンでも)

｢管理エリア」→｢アプリケーション｣から
システムOAuthアプリケーションを一つ登録すると、
同じ画面を開いた時に500エラーが発生します。

恐らく、 #5 と同様のエラーで
  app/views/admin/applications/index.html.haml 内

``` ruby
%td= render 'delete_form', application: application
↓
%td= render 'delete_form', application: アプリケーション
```
と置換しているためだと思います。

https://github.com/ksoichiro/gitlab-i18n-patch/blob/master/patches/v8.15.4/app_ja.patch#L1782-L1785

## エラー発生時ログ

```
 Processing by Admin::ApplicationsController#index as HTML
Completed 500 Internal Server Error in 65ms (ActiveRecord: 3.5ms)

ActionView::Template::Error (undefined local variable or method `アプリケーション' for #<#<Class:0x007fa2fdf41f58>:0x007fa2f59aeaa8>):
    20:         %td= application.redirect_uri
    21:         %td= application.access_tokens.map(&:resource_owner_id).uniq.count
    22:         %td= link_to '編集', edit_admin_application_path(application), class: 'btn btn-link'
    23:         %td= render 'delete_form', application: アプリケーション
  app/views/admin/applications/index.html.haml:23:in `block in _app_views_admin_applications_index_html_haml___1776353146759329648_70168936289920'
  app/views/admin/applications/index.html.haml:17:in `_app_views_admin_applications_index_html_haml___1776353146759329648_70168936289920'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
````

**Comment by ksoichiro** [comment]
ご指摘ありがとうございます！修正しました。

**Comment by hir-of** [comment]
対応ありがとうございました。
今後もよろしくお願いします。
